[build]
publish = "theme"
command = "npm run build"

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"


[[redirects]]
  from = "/s/*"
  to = "/s?:splat"

[[redirects]]
  from = "/external/play"
  to = "/s?:splat"

[[redirects]]
  from = "/external/add_shop"
  to = "/s?:splat"

[[redirects]]
  from = "/external/feedback"
  to = "https://play.google.com/store/apps/details?id=app.honestore.android"